# 🚢 Pandas on Real Data — Titanic Dataset
### Spring of Code — Artificial Intelligence (ML & Deep Learning)
**Instructor:** Asad Ullah | Research Assistant, DIP Lab

---

## 🎯 Goal of This Notebook

We will take the **raw Titanic dataset** — exactly as downloaded from Kaggle —  
and apply **every Pandas concept** we have learned to turn it into **clean, model-ready data**.

```
RAW CSV  →  Load  →  Explore  →  Clean  →  Transform  →  MODEL-READY DATA
```

This is the **exact workflow** a data scientist follows before building any ML model.

---

## 📋 Table of Contents
1. [About the Dataset](#1)
2. [Load the Data](#2)
3. [Step 1 — Explore (Understand the Data)](#3)
4. [Step 2 — Select & Index](#4)
5. [Step 3 — Filter & Analyse](#5)
6. [Step 4 — Handle Missing Values](#6)
7. [Step 5 — Clean & Transform](#7)
8. [Step 6 — Add New Features](#8)
9. [Step 7 — Sort, Group & Summarise](#9)
10. [Step 8 — Final Model-Ready Data](#10)

---

<a id='1'></a>
## 1. 🚢 About the Titanic Dataset

The **RMS Titanic** sank on 15 April 1912 after hitting an iceberg.  
Of the **2,224 passengers and crew**, only **710 survived**.  

This dataset contains information about **891 passengers** and whether they survived.

### Column Dictionary

| Column | Description | Type |
|--------|-------------|------|
| `PassengerId` | Unique ID for each passenger | Integer |
| `Survived` | 0 = Died, 1 = Survived | Integer (Target) |
| `Pclass` | Ticket class: 1 = 1st, 2 = 2nd, 3 = 3rd | Integer |
| `Name` | Full name of passenger | String |
| `Sex` | male / female | String |
| `Age` | Age in years | Float (has missing) |
| `SibSp` | # of siblings/spouses aboard | Integer |
| `Parch` | # of parents/children aboard | Integer |
| `Ticket` | Ticket number | String |
| `Fare` | Passenger fare (price paid) | Float |
| `Cabin` | Cabin number | String (mostly missing) |
| `Embarked` | Port of Embarkation: C=Cherbourg, Q=Queenstown, S=Southampton | String |

> 📥 **Download:** Go to `kaggle.com/c/titanic` → Data tab → Download `train.csv`

In [6]:
import shutil
shutil.unpack_archive('titanic.zip', 'titanic2')

<a id='2'></a>
## 2. 📥 Load the Data

In [97]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy  version:", np.__version__)

Pandas version: 2.3.3
NumPy  version: 2.2.6

In [98]:
print('titanic\\train.csv')
# print('Pakistan')

titanic\train.csv

In [99]:
shape = (600, 550)
shape[0]

600

In [100]:
# Load the raw CSV file
# Make sure train.csv is in the same folder as this notebook
df = pd.read_csv(r'dataset\titanic\train.csv')

print("Dataset loaded successfully!")
print(f'Shape: {df.shape}')
print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")

Dataset loaded successfully!
Shape: (891, 12)
Shape: 891 rows × 12 columns

In [101]:
# Always look at the first few rows immediately after loading
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<a id='3'></a>
## 3. 🔍 Step 1 — Explore (Understand the Data)

> **Rule:** Never touch the data before you fully understand it.  
> These commands are the **first 5 minutes** of every real data science project.

### 3.1 Shape & Basic Info

In [102]:
# How big is the dataset?
print("Shape  :", df.shape)
print("Rows   :", df.shape[0], "passengers")
print("Columns:", df.shape[1], "features")

Shape  : (891, 12)
Rows   : 891 passengers
Columns: 12 features

In [103]:
# Column names
print("Columns:", df.columns.tolist())

Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [104]:
# Last 5 rows — to see if data is consistent throughout
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [105]:
# ── df.info() — the most important first look ──
# Shows: column name, non-null count, dtype
# This INSTANTLY reveals which columns have missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [106]:
# ── df.describe() — statistical summary ──
# Only numerical columns by default
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [107]:
# Include ALL columns (strings too)
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

### 3.2 Data Types

In [108]:
# What type is each column?
print("Data types:")
print(df.dtypes)
print()

# Observation: Survived and Pclass are integers but they are CATEGORIES
# We will fix this later

Data types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### 3.3 Unique Values per Column

In [109]:
# Count unique values in each column
print("Unique values per column:")
print(df.nunique())
print()
# Notice:
# PassengerId → 891 unique (every passenger is unique) — useless for ML
# Survived    → 2 unique (0 or 1)
# Pclass      → 3 unique (1, 2, 3)
# Name        → 891 unique — every name different
# Sex         → 2 unique (male, female)
# Ticket      → 681 unique — mostly unique, won't help ML
# Cabin       → 147 unique but mostly missing

Unique values per column:
PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [110]:
print(f'{0.0009:.3f}')

0.001

In [111]:
# Distribution of key categorical columns
print("Survived (0=Died, 1=Survived):")
print(df['Survived'].value_counts())
print(f"\nSurvival rate: {df['Survived'].mean()*100:.1f}%")

Survived (0=Died, 1=Survived):
Survived
0    549
1    342
Name: count, dtype: int64

Survival rate: 38.4%

In [112]:
print("Passenger Class:")
print(df['Pclass'].value_counts().sort_index())
print()
print("Sex:")
print(df['Sex'].value_counts())
print()
print("Embarked (Port):")
print(df['Embarked'].value_counts())

Passenger Class:
Pclass
1    216
2    184
3    491
Name: count, dtype: int64

Sex:
Sex
male      577
female    314
Name: count, dtype: int64

Embarked (Port):
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

### 3.4 Missing Values — Full Picture

In [113]:
df.isnull().sum().sum()

np.int64(866)

In [114]:
df.size

10692

In [115]:
# Count missing per column
missing_count = df.isnull().sum()
missing_pct   = (df.isnull().sum() / len(df) * 100).round(1)

missing_report = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %':     missing_pct
})
missing_report = missing_report[missing_report['Missing Count'] > 0]
print("Columns with missing values:")
print(missing_report)
print()
print("Total missing values in dataset:", df.isnull().sum().sum())

Columns with missing values:
          Missing Count  Missing %
Age                 177       19.9
Cabin               687       77.1
Embarked              2        0.2

Total missing values in dataset: 866

In [116]:
# Decision time — what do we do with each missing column?
print("""
Missing Value Strategy:
─────────────────────────────────────────────────────
Age      → 19.9% missing → Fill with MEDIAN age
Cabin    → 77.1% missing → DROP the column (too many missing)
Embarked →  0.2% missing → Fill with MODE (most common port)
─────────────────────────────────────────────────────
""")

Missing Value Strategy:
─────────────────────────────────────────────────────
Age      → 19.9% missing → Fill with MEDIAN age
Cabin    → 77.1% missing → DROP the column (too many missing)
Embarked →  0.2% missing → Fill with MODE (most common port)
─────────────────────────────────────────────────────

<a id='4'></a>
## 4. 🎯 Step 2 — Select & Index

Practice `loc`, `iloc`, and column selection on real passenger data.

### 4.1 Column Selection

In [117]:
# Select a single column → Series
ages = df['Age']
print("Type:", type(ages))
print(ages.head(10))

Type: <class 'pandas.core.series.Series'>
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [118]:
# Select multiple columns → DataFrame
key_cols = df[['Name', 'Sex', 'Age', 'Pclass', 'Survived']]
print("Key columns:")
key_cols.head(8)

Key columns:

,Name,Sex,Age,Pclass,Survived
0,"Braund, Mr. Owen Harris",male,22.0,3,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1
2,"Heikkinen, Miss. Laina",female,26.0,3,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,1
4,"Allen, Mr. William Henry",male,35.0,3,0
5,"Moran, Mr. James",male,NaN,3,0
6,"McCarthy, Mr. Timothy J",male,54.0,1,0
7,"Palsson, Master. Gosta Leonard",male,2.0,3,0

### 4.2 iloc — Integer Position

In [119]:
# First passenger's record
print("First passenger (iloc[0]):")
print(df.iloc[0])

First passenger (iloc[0]):
PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [120]:
# Last passenger's record
print("Last passenger (iloc[-1]):")
print(df.iloc[-1])

Last passenger (iloc[-1]):
PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [121]:
last = df.iloc[-1]
last['Age']

np.float64(32.0)

In [122]:
# First 5 passengers, first 5 columns
print("First 5 rows, first 5 columns:")
df.iloc[0:5, 0:5]

First 5 rows, first 5 columns:

,PassengerId,Survived,Pclass,Name,Sex
0,1,0,3,"Braund, Mr. Owen Harris",male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
2,3,1,3,"Heikkinen, Miss. Laina",female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,5,0,3,"Allen, Mr. William Henry",male

In [123]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [124]:
df2 = df.iloc[::100]
df2[['Name', 'Age', 'Pclass', 'Survived']]

                                                  Name   Age  Pclass  Survived
0                              Braund, Mr. Owen Harris  22.0       3         0
100                            Petranec, Miss. Matilda  28.0       3         0
200                     Vande Walle, Mr. Nestor Cyriel  28.0       3         0
300           Kelly, Miss. Anna Katherine "Annie Kate"   NaN       3         1
400                                 Niskanen, Mr. Juha  39.0       3         1
500                                   Calic, Mr. Petar  17.0       3         0
600  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  24.0       2         1
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.0       1         1
800                               Ponesell, Mr. Martin  34.0       2         0

In [125]:
# Every 100th passenger — sampling to check data consistency
print("Every 100th passenger:")
print(df.iloc[::100][['Name', 'Age', 'Pclass', 'Survived']])

Every 100th passenger:
                                                  Name   Age  Pclass  Survived
0                              Braund, Mr. Owen Harris  22.0       3         0
100                            Petranec, Miss. Matilda  28.0       3         0
200                     Vande Walle, Mr. Nestor Cyriel  28.0       3         0
300           Kelly, Miss. Anna Katherine "Annie Kate"   NaN       3         1
400                                 Niskanen, Mr. Juha  39.0       3         1
500                                   Calic, Mr. Petar  17.0       3         0
600  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  24.0       2         1
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.0       1         1
800                               Ponesell, Mr. Martin  34.0       2         0

### 4.3 loc — Label Based

In [126]:
# Single passenger by row label
print("Passenger at row label 5:")
df.loc[5, ['Name', 'Age', 'Sex', 'Pclass', 'Survived']]

Passenger at row label 5:

Name        Moran, Mr. James
Age                      NaN
Sex                     male
Pclass                     3
Survived                   0
Name: 5, dtype: object

In [127]:
# Rows 0 to 4, specific columns by name
print("Rows 0-4, selected columns:")
print(df.loc[0:4, 'Name':'Age'])   # stop IS included in loc

Rows 0-4, selected columns:
                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [128]:
# Set PassengerId as index — now we can look up by passenger ID
df_indexed = df.set_index('PassengerId')
print("Lookup Passenger #10:")
print(df_indexed.loc[10, ['Name', 'Age', 'Sex', 'Survived']])
print()
print(df.loc[9, ['Name', 'Age', 'Sex', 'Survived']])

Lookup Passenger #10:
Name        Nasser, Mrs. Nicholas (Adele Achem)
Age                                        14.0
Sex                                      female
Survived                                      1
Name: 10, dtype: object

Name        Nasser, Mrs. Nicholas (Adele Achem)
Age                                        14.0
Sex                                      female
Survived                                      1
Name: 9, dtype: object

<a id='5'></a>
## 5. 🔎 Step 3 — Filter & Analyse

Ask real questions about the data using filtering.

### 5.1 Single Condition Filters

In [129]:
mask = df['Survived'] == 1

In [130]:
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [131]:
# Who survived?
survivors = df[df['Survived'] == 1]
print(f"Survivors: {len(survivors)} passengers")
survivors[['Name', 'Sex', 'Age', 'Pclass']].head()

Survivors: 342 passengers

                                                Name     Sex   Age  Pclass
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1
2                             Heikkinen, Miss. Laina  female  26.0       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0       3
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0       2

In [132]:
# Who was in 1st class?
first_class = df[df['Pclass'] == 1]
print(f"First class passengers: {len(first_class)}")
first_class[['Name', 'Age', 'Fare', 'Survived']].head()

First class passengers: 216

                                                 Name   Age     Fare  Survived
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833         1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000         1
6                             McCarthy, Mr. Timothy J  54.0  51.8625         0
11                           Bonnell, Miss. Elizabeth  58.0  26.5500         1
23                       Sloper, Mr. William Thompson  28.0  35.5000         1

In [133]:
# Children (under 12)
children = df[df['Age'] < 12]
print(f"Children aboard: {len(children)}")
print(f"Children survived: {children['Survived'].sum()}")
print(f"Children survival rate: {children['Survived'].mean()*100:.1f}%")

Children aboard: 68
Children survived: 39
Children survival rate: 57.4%

In [134]:
# Passengers who paid more than 100 in fare
high_fare = df[df['Fare'] > 100]
print(f"High-fare passengers (>100): {len(high_fare)}")
high_fare[['Name', 'Pclass', 'Fare', 'Survived']].head()

High-fare passengers (>100): 53

,Name,Pclass,Fare,Survived
27,"Fortune, Mr. Charles Alexander",1,263.0000,0
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,146.5208,1
88,"Fortune, Miss. Mabel Helen",1,263.0000,1
118,"Baxter, Mr. Quigg Edmond",1,247.5208,0
195,"Lurette, Miss. Elise",1,146.5208,1

### 5.2 Multiple Condition Filters

In [135]:
# Female survivors from 1st class
female_1st_survived = df[
    (df['Sex'] == 'female') &
    (df['Pclass'] == 1) &
    (df['Survived'] == 1)
]
print(f"Female 1st class survivors: {len(female_1st_survived)}")
female_1st_survived[['Name', 'Age', 'Fare']].head()

Female 1st class survivors: 91

                                                 Name   Age      Fare
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0   71.2833
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0   53.1000
11                           Bonnell, Miss. Elizabeth  58.0   26.5500
31     Spencer, Mrs. William Augustus (Marie Eugenie)   NaN  146.5208
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  49.0   76.7292

In [136]:
# Male passengers from 2nd OR 3rd class who died
male_low_class_died = df[
    (df['Sex'] == 'male') &
    (df['Pclass'].isin([2, 3])) &
    (df['Survived'] == 0)
]
print(f"Male 2nd/3rd class who died: {len(male_low_class_died)}")

Male 2nd/3rd class who died: 391

In [137]:
# Adults (18-60) who were travelling alone (no siblings/spouses, no parents/children)
alone = df[
    (df['Age'].between(18, 60)) &
    (df['SibSp'] == 0) &
    (df['Parch'] == 0)
]
print(f"Adult solo travellers: {len(alone)}")
print(f"Their survival rate: {alone['Survived'].mean()*100:.1f}%")

Adult solo travellers: 363
Their survival rate: 32.0%

In [138]:
# Passengers who embarked from Cherbourg (C) and survived
cherbourg_survived = df[
    (df['Embarked'] == 'C') &
    (df['Survived'] == 1)
]
print(f"Cherbourg survivors: {len(cherbourg_survived)}")

Cherbourg survivors: 93

### 5.3 Quick Survival Analysis (Filter + Select)

In [139]:
# Survival rate by gender — using filters
female_survival = df[df['Sex'] == 'female']['Survived'].mean()
male_survival   = df[df['Sex'] == 'male']['Survived'].mean()

print("Survival Rates by Gender:")
print(f"  Female: {female_survival*100:.1f}%")
print(f"  Male  : {male_survival*100:.1f}%")
print(f"  → Women were {female_survival/male_survival:.1f}x more likely to survive")

Survival Rates by Gender:
  Female: 74.2%
  Male  : 18.9%
  → Women were 3.9x more likely to survive

In [140]:
# Survival rate by class — using filters
print("Survival Rates by Class:")

for cls in [1,2,3]:
    rate = df[df['Pclass'] == cls]['Survived'].mean()
    count = len(df[df['Pclass'] == cls])
    print(f"  Class {cls}: {rate*100:.1f}%  ({count} passengers)")

Survival Rates by Class:
  Class 1: 63.0%  (216 passengers)
  Class 2: 47.3%  (184 passengers)
  Class 3: 24.2%  (491 passengers)

<a id='6'></a>
## 6. 🩹 Step 4 — Handle Missing Values

We identified 3 columns with missing values. Now we fix them.

In [141]:
# Work on a copy — always preserve the original!
df_clean = df.copy()

print("Missing values BEFORE cleaning:")
df_clean.isnull().sum() > 0
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])

Missing values BEFORE cleaning:
Age         177
Cabin       687
Embarked      2
dtype: int64

### 6.1 Age — Fill with Median

In [142]:
# Why median and not mean?
print("Age statistics:")
print(f"  Mean  : {df_clean['Age'].mean():.2f}")
print(f"  Median: {df_clean['Age'].median():.2f}")
print(f"  Missing: {df_clean['Age'].isnull().sum()} passengers ({df_clean['Age'].isnull().mean()*100:.1f}%)")
print()
print("→ We use MEDIAN because age data can be skewed.")
print("  Median is more robust to outliers than mean.")

Age statistics:
  Mean  : 29.70
  Median: 28.00
  Missing: 177 passengers (19.9%)

→ We use MEDIAN because age data can be skewed.
  Median is more robust to outliers than mean.

In [143]:
# Fill missing Age with median
age_median = df_clean['Age'].median()
df_clean['Age'] = df_clean['Age'].fillna(age_median)

print(f"Age median used for fill: {age_median}")
print(f"Age missing after fill  : {df_clean['Age'].isnull().sum()}")

Age median used for fill: 28.0
Age missing after fill  : 0

### 6.2 Embarked — Fill with Mode

In [144]:
# Only 2 missing — use mode (most common port)
print("Embarked distribution:")
print(df_clean['Embarked'].value_counts())
print()

Embarked distribution:
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [145]:

embarked_mode = df_clean['Embarked'].mode()[0]
print(f"Most common port: '{embarked_mode}' (Southampton)")

Most common port: 'S' (Southampton)

In [146]:
# Show the 2 rows with missing Embarked before fixing
print("\nRows with missing Embarked:")
df_clean[df_clean['Embarked'].isnull()][['Name','Pclass','Fare','Embarked']]

Rows with missing Embarked:

                                          Name  Pclass  Fare Embarked
61                         Icard, Miss. Amelie       1  80.0      NaN
829  Stone, Mrs. George Nelson (Martha Evelyn)       1  80.0      NaN

In [147]:
# Fill with mode
df_clean['Embarked'] = df_clean['Embarked'].fillna(embarked_mode)
print(f"Embarked missing after fill: {df_clean['Embarked'].isnull().sum()}")

Embarked missing after fill: 0

### 6.3 Cabin — Drop the Column

In [148]:
# 77% missing — too much to fill reliably, drop the column
print(f"Cabin missing: {df_clean['Cabin'].isnull().sum()} out of {len(df_clean)} ({df_clean['Cabin'].isnull().mean()*100:.1f}%)")
print(f"→ Dropping Cabin column — {df_clean['Cabin'].isnull().mean()*100:.1f}% missing is too much to impute reliably.")

df_clean = df_clean.drop(columns=['Cabin'])
print("\nColumns after dropping Cabin:")
print(df_clean.columns.tolist())

Cabin missing: 687 out of 891 (77.1%)
→ Dropping Cabin column — 77.1% missing is too much to impute reliably.

Columns after dropping Cabin:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked']

In [149]:
# Verify — zero missing values remaining
print("Missing values AFTER cleaning:")
print(df_clean.isnull().sum())
print()
print(f"Total missing: {df_clean.isnull().sum().sum()}")

Missing values AFTER cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Total missing: 0

<a id='7'></a>
## 7. 🧹 Step 5 — Clean & Transform

Fix data types, remove useless columns, standardise values.

### 7.1 Drop Useless Columns

In [151]:
psngr_cor = np.corrcoef(df_clean['PassengerId'].values, df_clean['Survived'].values)

print('Correlation of PassengerId with Survived: ', psngr_cor[0,1])

Correlation of PassengerId with Survived:  -0.0050066607670664915

In [152]:
# PassengerId → just a row number, no predictive value
# Ticket      → mostly unique codes, no clear pattern
# Name        → too unique, but we will extract the title first (next step)

print("Columns before dropping useless ones:")
print(df_clean.columns.tolist())

df_clean = df_clean.drop(columns=['PassengerId', 'Ticket'])

print("\nColumns after dropping:")
print(df_clean.columns.tolist())

Columns before dropping useless ones:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked']

Columns after dropping:
['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

### 7.2 Fix Data Types

In [153]:
# Current dtypes
print("Current dtypes:")
print(df_clean.dtypes)
print()
print("Issues:")
print("  Survived → stored as int, but it is a category (0/1)")
print("  Pclass   → stored as int, but it is an ordered category (1,2,3)")
print("  Age      → float, should be fine")

Current dtypes:
Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked     object
dtype: object

Issues:
  Survived → stored as int, but it is a category (0/1)
  Pclass   → stored as int, but it is an ordered category (1,2,3)
  Age      → float, should be fine

In [154]:
# Convert Age from float to int (we filled NaN so no decimals needed)
df_clean['Age'] = df_clean['Age'].astype(int)

print("After type fix:")
print(df_clean.dtypes)

After type fix:
Survived      int64
Pclass        int64
Name         object
Sex          object
Age           int64
SibSp         int64
Parch         int64
Fare        float64
Embarked     object
dtype: object

### 7.3 Check for Duplicates

In [159]:
df_clean.duplicated().sum()

np.int64(0)

In [155]:
print(f"Duplicate rows: {df_clean.duplicated().sum()}")

# No duplicates in Titanic, but always check in real projects!
if df_clean.duplicated().sum() == 0:
    print("No duplicate rows found.")
else:
    df_clean = df_clean.drop_duplicates()
    print(f"Removed duplicates. New shape: {df_clean.shape}")

Duplicate rows: 0
No duplicate rows found.

### 7.4 Standardise Text Values

In [160]:
# Check Sex column values
print("Sex unique values:", df_clean['Sex'].unique())
print("Embarked unique values:", df_clean['Embarked'].unique())
# These look clean already — good.
# In messy real datasets you would often find 'Male', 'male', 'MALE' all mixed

Sex unique values: ['male' 'female']
Embarked unique values: ['S' 'C' 'Q']

In [161]:
# Rename 'Embarked' values to full port names for clarity
port_map = {'S': 'Southampton', 'C': 'Cherbourg', 'Q': 'Queenstown'}
df_clean['Embarked'] = df_clean['Embarked'].map(port_map)

print("Embarked after mapping:")
print(df_clean['Embarked'].value_counts())

Embarked after mapping:
Embarked
Southampton    646
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

<a id='8'></a>
## 8. 🛠️ Step 6 — Add New Features (Feature Engineering)

Creating new columns from existing ones — this is where Pandas skills directly power ML.

### 8.1 Extract Title from Name

In [162]:
# Passenger names follow this pattern: 'Last, Title. First'
print("Sample names:")
print(df_clean['Name'].head(8).tolist())

Sample names:
['Braund, Mr. Owen Harris', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss. Laina', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Allen, Mr. William Henry', 'Moran, Mr. James', 'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard']

In [169]:
name = 'Braund,  Mr. Owen Harris'
name.split(',')[1].strip().split('.')[0]

'Mr'

In [170]:
# Extract title using apply() + string split
def extract_title(name):
    # Name format: 'Braund, Mr. Owen Harris'
    # Split by comma → ['Braund', ' Mr. Owen Harris']
    # Take part after comma, split by dot → [' Mr', ' Owen Harris']
    # Take first part, strip spaces
    # ['']
    return name.split(',')[1].split('.')[0].strip()

df_clean['Title'] = df_clean['Name'].apply(extract_title)

print("All unique titles found:")
print(df_clean['Title'].value_counts())

All unique titles found:
Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [171]:
# Simplify rare titles into groups using map()
# Common: Mr, Miss, Mrs, Master
# Rare: Dr, Rev, Col, Major → group as 'Officer'
# Noble: Don, Lady, Sir, Countess, Jonkheer → group as 'Noble'

def simplify_title(title):
    if title in ['Mr']:                                        return 'Mr'
    elif title in ['Miss', 'Mlle', 'Ms']:                     return 'Miss'
    elif title in ['Mrs', 'Mme']:                             return 'Mrs'
    elif title in ['Master']:                                  return 'Master'
    elif title in ['Dr', 'Rev', 'Col', 'Major', 'Capt']:      return 'Officer'
    else:                                                      return 'Noble'

df_clean['Title'] = df_clean['Title'].apply(simplify_title)

print("Simplified titles:")
print(df_clean['Title'].value_counts())

Simplified titles:
Title
Mr         517
Miss       185
Mrs        126
Master      40
Officer     18
Noble        5
Name: count, dtype: int64

In [172]:
# Survival rate by title — interesting insight!
print("Survival rate by Title:")
title_survival = df_clean.groupby('Title')['Survived'].agg(['mean','count'])
title_survival.columns = ['Survival Rate', 'Count']
title_survival['Survival Rate'] = (title_survival['Survival Rate'] * 100).round(1)
print(title_survival.sort_values('Survival Rate', ascending=False))

Survival rate by Title:
         Survival Rate  Count
Title
Mrs               79.4    126
Miss              70.3    185
Noble             60.0      5
Master            57.5     40
Officer           27.8     18
Mr                15.7    517

In [173]:
# Now drop the Name column — we've extracted what we needed
df_clean = df_clean.drop(columns=['Name'])
print("Columns now:", df_clean.columns.tolist())

Columns now: ['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Title']

### 8.2 Age Groups

In [174]:
# Create AgeGroup column using apply()
def age_group(age):
    if age < 13:   return 'Child'     # 0-12
    elif age < 18: return 'Teen'      # 13-17
    elif age < 60: return 'Adult'     # 18-59
    else:          return 'Senior'    # 60+

df_clean['AgeGroup'] = df_clean['Age'].apply(age_group)

print("Age group distribution:")
print(df_clean['AgeGroup'].value_counts())

Age group distribution:
AgeGroup
Adult     752
Child      69
Teen       44
Senior     26
Name: count, dtype: int64

In [175]:
# Survival rate by age group
print("Survival rate by Age Group:")
ag_surv = df_clean.groupby('AgeGroup')['Survived'].mean() * 100
print(ag_surv.round(1))

Survival rate by Age Group:
AgeGroup
Adult     36.4
Child     58.0
Senior    26.9
Teen      47.7
Name: Survived, dtype: float64

### 8.3 Family Size

In [176]:
# SibSp = siblings + spouses
# Parch  = parents + children
# FamilySize = total family members on board (including self)

df_clean['FamilySize'] = df_clean['SibSp'] + df_clean['Parch'] + 1

print("Family size distribution:")
print(df_clean['FamilySize'].value_counts().sort_index())

Family size distribution:
FamilySize
1     537
2     161
3     102
4      29
5      15
6      22
7      12
8       6
11      7
Name: count, dtype: int64

In [177]:
# Is the passenger travelling alone?
df_clean['IsAlone'] = (df_clean['FamilySize'] == 1).astype(int)
# astype(int) converts True→1, False→0

alone_survival = df_clean.groupby('IsAlone')['Survived'].mean() * 100
print("Survival rate:")
print(f"  Travelling with family : {alone_survival[0]:.1f}%")
print(f"  Travelling alone       : {alone_survival[1]:.1f}%")

Survival rate:
  Travelling with family : 50.6%
  Travelling alone       : 30.4%

### 8.4 Fare Bands

In [178]:
# Fare distribution
print("Fare statistics:")
print(df_clean['Fare'].describe().round(2))

Fare statistics:
count    891.00
mean      32.20
std       49.69
min        0.00
25%        7.91
50%       14.45
75%       31.00
max      512.33
Name: Fare, dtype: float64

In [179]:
# Create Fare bands using apply()
def fare_band(fare):
    if   fare <= 10:  return 'Low'
    elif fare <= 30:  return 'Medium'
    elif fare <= 100: return 'High'
    else:             return 'Very High'

df_clean['FareBand'] = df_clean['Fare'].apply(fare_band)

print("Fare band distribution:")
print(df_clean['FareBand'].value_counts())
print()
print("Survival rate by Fare Band:")
fare_surv = df_clean.groupby('FareBand')['Survived'].mean() * 100
print(fare_surv.round(1))

Fare band distribution:
FareBand
Low          336
Medium       321
High         181
Very High     53
Name: count, dtype: int64

Survival rate by Fare Band:
FareBand
High         53.6
Low          19.9
Medium       43.3
Very High    73.6
Name: Survived, dtype: float64

<a id='9'></a>
## 9. 📊 Step 7 — Sort, Group & Summarise

Deep analysis using `sort_values`, `groupby`, and `agg`.

### 9.1 Sorting

In [180]:
# Top 10 passengers who paid the most
print("Top 10 highest fares paid:")
print(df_clean.sort_values('Fare', ascending=False)
              [['Sex', 'Age', 'Pclass', 'Fare', 'Survived']]
              .head(10))

Top 10 highest fares paid:
        Sex  Age  Pclass      Fare  Survived
679    male   36       1  512.3292         1
258  female   35       1  512.3292         1
737    male   35       1  512.3292         1
88   female   23       1  263.0000         1
438    male   64       1  263.0000         0
341  female   24       1  263.0000         1
27     male   19       1  263.0000         0
742  female   21       1  262.3750         1
311  female   18       1  262.3750         1
299  female   50       1  247.5208         1

In [181]:
# Youngest passengers
print("10 youngest passengers:")
print(df_clean.sort_values('Age')
              [['Sex', 'Age', 'Pclass', 'FamilySize', 'Survived']]
              .head(10))

10 youngest passengers:
        Sex  Age  Pclass  FamilySize  Survived
831    male    0       2           3         1
305    male    0       1           4         1
78     male    0       2           3         1
803    male    0       3           2         1
755    male    0       2           3         1
469  female    0       3           4         1
644  female    0       3           4         1
381  female    1       3           3         1
827    male    1       2           3         1
788    male    1       3           4         1

In [184]:
# Sort by class then by fare (highest fare in each class first)
print("Sorted by Pclass then Fare (desc):")
print(df_clean.sort_values(['Pclass', 'Fare'], ascending=[True, False])
              [['Pclass', 'Fare', 'Sex', 'Survived']]
              .head(10))

Sorted by Pclass then Fare (desc):
     Pclass      Fare     Sex  Survived
258       1  512.3292  female         1
679       1  512.3292    male         1
737       1  512.3292    male         1
27        1  263.0000    male         0
88        1  263.0000  female         1
341       1  263.0000  female         1
438       1  263.0000    male         0
311       1  262.3750  female         1
742       1  262.3750  female         1
118       1  247.5208    male         0

### 9.2 Groupby Analysis

In [185]:
# Comprehensive survival analysis by class and sex
print("Survival rate by Class and Sex:")
class_sex = df_clean.groupby(['Pclass', 'Sex'])['Survived'].agg(['sum', 'count', 'mean'])
class_sex.columns = ['Survived', 'Total', 'Survival Rate']
class_sex['Survival Rate'] = (class_sex['Survival Rate'] * 100).round(1)
class_sex

Survival rate by Class and Sex:

               Survived  Total  Survival Rate
Pclass Sex
1      female        91     94           96.8
       male          45    122           36.9
2      female        70     76           92.1
       male          17    108           15.7
3      female        72    144           50.0
       male          47    347           13.5

In [186]:
# Average fare by class
print("Average fare by Passenger Class:")
print(df_clean.groupby('Pclass')['Fare'].agg(['mean', 'min', 'max']).round(2))

Average fare by Passenger Class:
         mean  min     max
Pclass
1       84.15  0.0  512.33
2       20.66  0.0   73.50
3       13.68  0.0   69.55

In [187]:
# Survival by embarkation port
print("Survival by Embarkation Port:")
port_stats = df_clean.groupby('Embarked').agg(
    Total      = ('Survived', 'count'),
    Survived   = ('Survived', 'sum'),
    Surv_Rate  = ('Survived', 'mean'),
    Avg_Fare   = ('Fare',     'mean')
).round(2)
port_stats['Surv_Rate'] = (port_stats['Surv_Rate'] * 100).round(1)
print(port_stats)

Survival by Embarkation Port:
             Total  Survived  Surv_Rate  Avg_Fare
Embarked
Cherbourg      168        93       55.0     59.95
Queenstown      77        30       39.0     13.28
Southampton    646       219       34.0     27.24

In [188]:
# Average age by class and sex
print("Average age by Class and Sex:")
print(df_clean.groupby(['Pclass', 'Sex'])['Age'].mean().round(1))

Average age by Class and Sex:
Pclass  Sex
1       female    34.0
        male      39.0
2       female    28.7
        male      30.5
3       female    23.6
        male      26.9
Name: Age, dtype: float64

In [189]:
# Family size vs survival
print("Survival rate by Family Size:")
fam_surv = df_clean.groupby('FamilySize').agg(
    Count       = ('Survived', 'count'),
    Surv_Rate   = ('Survived', 'mean')
)
fam_surv['Surv_Rate'] = (fam_surv['Surv_Rate'] * 100).round(1)
print(fam_surv)

Survival rate by Family Size:
            Count  Surv_Rate
FamilySize
1             537       30.4
2             161       55.3
3             102       57.8
4              29       72.4
5              15       20.0
6              22       13.6
7              12       33.3
8               6        0.0
11              7        0.0

<a id='10'></a>
## 10. Step 8 — Final Model-Ready Data

The last step: encode categorical columns into numbers so an ML model can read them.

In [190]:
# Where are we now?
print("Current DataFrame:")
df_clean.head()

Current DataFrame:

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title,AgeGroup,FamilySize,IsAlone,FareBand
0,0,3,male,22,1,0,7.2500,Southampton,Mr,Adult,2,0,Low
1,1,1,female,38,1,0,71.2833,Cherbourg,Mrs,Adult,2,0,High
2,1,3,female,26,0,0,7.9250,Southampton,Miss,Adult,1,1,Low
3,1,1,female,35,1,0,53.1000,Southampton,Mrs,Adult,2,0,High
4,0,3,male,35,0,0,8.0500,Southampton,Mr,Adult,1,1,Low

In [191]:
print("Current dtypes:")
print(df_clean.dtypes)
print()
print("Remaining categorical (string) columns to encode:")
cat_cols = df_clean.select_dtypes(include='object').columns.tolist()
print(cat_cols)

Current dtypes:
Survived        int64
Pclass          int64
Sex            object
Age             int64
SibSp           int64
Parch           int64
Fare          float64
Embarked       object
Title          object
AgeGroup       object
FamilySize      int64
IsAlone         int64
FareBand       object
dtype: object

Remaining categorical (string) columns to encode:
['Sex', 'Embarked', 'Title', 'AgeGroup', 'FareBand']

### 10.1 Encode Binary Column — Sex

In [192]:
# Sex: male → 0, female → 1
df_clean['Sex'] = df_clean['Sex'].map({'male': 0, 'female': 1})

print("Sex after encoding:")
print(df_clean['Sex'].value_counts())

Sex after encoding:
Sex
0    577
1    314
Name: count, dtype: int64

### 10.2 Encode Multi-Class Columns — Embarked, Title, AgeGroup, FareBand

In [193]:
# Embarked: Southampton→0, Cherbourg→1, Queenstown→2
embarked_map = {'Southampton': 0, 'Cherbourg': 1, 'Queenstown': 2}
df_clean['Embarked'] = df_clean['Embarked'].map(embarked_map)

# Title: encode as numbers
title_map = {'Mr': 0, 'Miss': 1, 'Mrs': 2, 'Master': 3, 'Officer': 4, 'Noble': 5}
df_clean['Title'] = df_clean['Title'].map(title_map)

# AgeGroup: Child→0, Teen→1, Adult→2, Senior→3
age_map = {'Child': 0, 'Teen': 1, 'Adult': 2, 'Senior': 3}
df_clean['AgeGroup'] = df_clean['AgeGroup'].map(age_map)

# FareBand: Low→0, Medium→1, High→2, Very High→3
fare_map_enc = {'Low': 0, 'Medium': 1, 'High': 2, 'Very High': 3}
df_clean['FareBand'] = df_clean['FareBand'].map(fare_map_enc)

print("Encoding done!")
print(df_clean.dtypes)

Encoding done!
Survived        int64
Pclass          int64
Sex             int64
Age             int64
SibSp           int64
Parch           int64
Fare          float64
Embarked        int64
Title           int64
AgeGroup        int64
FamilySize      int64
IsAlone         int64
FareBand        int64
dtype: object

### 10.3 Drop Redundant Columns

In [194]:
# We now have AgeGroup and FareBand which are better than raw Age and Fare
# We also have FamilySize which captures SibSp + Parch together
# So we can drop: Age, Fare, SibSp, Parch

df_clean = df_clean.drop(columns=['SibSp', 'Parch'])

print("Final columns:")
print(df_clean.columns.tolist())

Final columns:
['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Title', 'AgeGroup', 'FamilySize', 'IsAlone', 'FareBand']

### 10.4 Final Check

In [195]:
print("=" * 50)
print("       FINAL MODEL-READY DATASET")
print("=" * 50)
print()
df_clean.head(10)

==================================================
       FINAL MODEL-READY DATASET
==================================================

,Survived,Pclass,Sex,Age,Fare,Embarked,Title,AgeGroup,FamilySize,IsAlone,FareBand
0,0,3,0,22,7.2500,0,0,2,2,0,0
1,1,1,1,38,71.2833,1,2,2,2,0,2
2,1,3,1,26,7.9250,0,1,2,1,1,0
3,1,1,1,35,53.1000,0,2,2,2,0,2
4,0,3,0,35,8.0500,0,0,2,1,1,0
5,0,3,0,28,8.4583,2,0,2,1,1,0
6,0,1,0,54,51.8625,0,0,2,1,1,2
7,0,3,0,2,21.0750,0,3,0,5,0,1
8,1,3,1,27,11.1333,0,2,2,3,0,1
9,1,2,1,14,30.0708,1,2,1,2,0,2

In [196]:
print("Final shape       :", df_clean.shape)
print("Missing values    :", df_clean.isnull().sum().sum())
print("Duplicate rows    :", df_clean.duplicated().sum())
print("All numeric       :", (df_clean.dtypes != 'object').all())
print()
print("Column dtypes:")
print(df_clean.dtypes)

Final shape       : (891, 11)
Missing values    : 0
Duplicate rows    : 113
All numeric       : True

Column dtypes:
Survived        int64
Pclass          int64
Sex             int64
Age             int64
Fare          float64
Embarked        int64
Title           int64
AgeGroup        int64
FamilySize      int64
IsAlone         int64
FareBand        int64
dtype: object

In [197]:
# Statistical summary of the final clean dataset
print("Statistical summary:")
df_clean.describe().round(2)

Statistical summary:

,Survived,Pclass,Sex,Age,Fare,Embarked,Title,AgeGroup,FamilySize,IsAlone,FareBand
count,891.00,891.00,891.00,891.00,891.00,891.00,891.00,891.00,891.00,891.00,891.00
mean,0.38,2.31,0.35,29.35,32.20,0.36,0.73,1.82,1.90,0.60,0.95
std,0.49,0.84,0.48,13.03,49.69,0.64,1.05,0.60,1.61,0.49,0.90
min,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00
25%,0.00,2.00,0.00,22.00,7.91,0.00,0.00,2.00,1.00,0.00,0.00
50%,0.00,3.00,0.00,28.00,14.45,0.00,0.00,2.00,1.00,1.00,1.00
75%,1.00,3.00,1.00,35.00,31.00,1.00,1.00,2.00,2.00,1.00,2.00
max,1.00,3.00,1.00,80.00,512.33,2.00,5.00,3.00,11.00,1.00,3.00

### 10.5 Separate Features (X) and Target (y)

In [198]:
# X = features (what we use to predict)
# y = target   (what we want to predict)

X = df_clean.drop(columns=['Survived'])   # all columns except target
y = df_clean['Survived']                  # the target column

print("Features (X):")
print(f"  Shape  : {X.shape}")
print(f"  Columns: {X.columns.tolist()}")
print()
print("Target (y):")
print(f"  Shape  : {y.shape}")
print(f"  Values : {y.value_counts().to_dict()}")
print(f"  (0=Died, 1=Survived)")

Features (X):
  Shape  : (891, 10)
  Columns: ['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Title', 'AgeGroup', 'FamilySize', 'IsAlone', 'FareBand']

Target (y):
  Shape  : (891,)
  Values : {0: 549, 1: 342}
  (0=Died, 1=Survived)

In [199]:
# Save cleaned data to CSV for future use
df_clean.to_csv('titanic_clean.csv', index=False)
print("Saved to titanic_clean.csv")
print(f"   {df_clean.shape[0]} rows × {df_clean.shape[1]} columns")

Saved to titanic_clean.csv
   891 rows × 11 columns

---

## 🎯 What We Did — Full Summary

```
RAW TITANIC DATA (891 rows × 12 columns)
           ↓
✅ Explored   → shape, info, describe, dtypes, value_counts, nunique
✅ Selected   → loc, iloc, column selection
✅ Filtered   → single condition, AND, OR, NOT, isin, between
✅ Missing    → isnull, fillna(median), fillna(mode), dropna, drop(column)
✅ Cleaned    → drop useless cols, fix dtypes, check duplicates
✅ Renamed    → map() to rename Embarked port codes
✅ Engineered → apply() for Title, AgeGroup, FareBand, FamilySize, IsAlone
✅ Sorted     → sort_values on Fare, Age, multi-column
✅ Grouped    → groupby + agg for survival analysis by class, sex, port
✅ Encoded    → map() to convert all strings to numbers
✅ Exported   → to_csv to save the clean file
           ↓
MODEL-READY DATA (891 rows × 8 columns) — all numeric, zero missing
```

| Pandas Concept | Where We Used It |
|----------------|------------------|
| `pd.read_csv` | Load raw Titanic CSV |
| `head`, `tail`, `info`, `describe` | Step 1 — Explore |
| `dtypes`, `nunique`, `value_counts` | Step 1 — Explore |
| `isnull`, `sum`, `mean` | Detect missing values |
| `iloc`, `loc` | Step 2 — Select & Index |
| `[]`, `[[]]` | Column selection |
| Boolean filters, `isin`, `between` | Step 3 — Filter |
| `fillna(median)`, `fillna(mode)` | Step 4 — Handle Missing |
| `drop(columns)`, `dropna` | Drop Cabin, useless cols |
| `astype` | Fix Age dtype |
| `duplicated`, `drop_duplicates` | Check duplicates |
| `map` | Rename ports, encode categories |
| `apply` | Extract Title, create AgeGroup, FareBand |
| `sort_values` | Sort by Fare, Age |
| `groupby`, `agg` | Survival analysis |
| `to_csv` | Save clean file |

> 🚀 **Next Class:** We will load `titanic_clean.csv` and build our **first ML model** on this clean data!